name: if_app
description: Couple communication and relationship management app.
publish_to: "none"
version: 0.1.0+3

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.0
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  http: ^1.2.2
  url_launcher: ^6.3.1
  image_picker: ^1.0.7
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.15.0
  geocoding: ^3.0.0
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  shared_preferences: ^2.3.3
  kakao_flutter_sdk: ^1.10.0
  flutter_line_sdk: ^2.7.0
  firebase_messaging: ^15.2.10
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
